package skill

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/coco-papiyon/korobokcle/internal/config"
	"github.com/google/uuid"
)

type MockProvider struct{}

func NewMockProvider() *MockProvider {
	return &MockProvider{}
}

func (p *MockProvider) Run(_ context.Context, req AIRequest) (AIResult, error) {
	output := "## Goal\n\nMock provider goal.\n\n## Scope\n\nMock provider scope.\n\n## Assumptions\n\n- Mock execution.\n\n## Proposed Changes\n\n- This artifact was generated by the mock provider.\n\n## Risks\n\n- Output is synthetic.\n\n## Test Strategy\n\n- Verify the artifact files are written.\n"
	if req.SkillName == "implement" {
		output = "## 実装内容の要約\n\n- Approved design を確認したうえで、実装フローを通すための mock patch を生成します。\n\n## 変更した箇所\n\n- 追跡対象外の artifacts 配下に mock 用の記録ファイルを追加します。\n\n## 動作確認\n\n- パッチ適用と result.md の保存経路を確認します。\n\n## 懸念点・残課題\n\n- 実コードの変更は行いません。\n\n## ブランチ名\n\nfeature/mock-implementation\n\n## Patch\n\n```diff\ndiff --git a/artifacts/mock-implementation.txt b/artifacts/mock-implementation.txt\nnew file mode 100644\n--- /dev/null\n+++ b/artifacts/mock-implementation.txt\n@@ -0,0 +1 @@\n+mock implementation applied\n```\n"
	}
	if req.SkillName == "implement_fix" {
		output = "## 修正内容の要約\n\n- 失敗したテストを踏まえて mock patch を再生成します。\n\n## 変更した箇所\n\n- 追跡対象外の artifacts 配下に実装修正用の記録ファイルを追加します。\n\n## 再確認内容\n\n- パッチ適用と result.md の保存経路を確認します。\n\n## 懸念点・残課題\n\n- 実コードの変更は行いません。\n\n## ブランチ名\n\nimplement_fix/mock-implementation\n\n## Patch\n\n```diff\ndiff --git a/artifacts/mock-implement-fix.txt b/artifacts/mock-implement-fix.txt\nnew file mode 100644\n--- /dev/null\n+++ b/artifacts/mock-implement-fix.txt\n@@ -0,0 +1 @@\n+mock implement fix applied\n```\n"
	}
	if req.SkillName == "review" {
		output = "## Summary\n\n- Reviewed the pull request context.\n\n## Findings\n\n- No real review was performed by the mock provider.\n\n## Recommendations\n\n- Verify the changes manually.\n\n## Notes\n\n- This output is synthetic.\n"
	}
	if req.SkillName == "improvement_consideration" {
		output = "# 改善方針案\n\n## タイトル\n\nMock provider が汎化した改善方針\n\n## 適用対象\n\n- repository: mock/repository\n- phases: design\n- sourceEvent: design_rerun_requested\n\n## 改善項目\n\n- 画面レイアウト方針\n  - 画面ごとの主要アクションと補足説明の配置ルールを明文化する\n\n## 汎化メモ\n\n- 元コメントを継続利用できる指示へ整理した mock 出力です。\n\n## 元コメント\n\nXX画面で、ボタンを左に、説明を右に配置する\n"
	}
	if req.SkillName == "improvement_implementation" {
		output = "# 改善実装結果\n\n## 修正箇所一覧\n\n- improvement workspace のソースコードを直接修正\n- `.improvement/design.md` を最終要約として更新\n\n## 変更したファイル\n\n- `src/example.go`\n- `.improvement/design.md`\n\n## 追加した処理\n\n- 改善案を直接コードに反映する処理\n\n## 変更した処理\n\n- 既存の実装を改善案ベースへ置き換え\n\n## 動作確認\n\n- mock provider の出力を書き込み可能であることを確認\n\n## 懸念点・残課題\n\n- 実コードの変更は mock のため行っていません。\n"
	}
	return AIResult{
		Stdout: "mock provider executed",
		Output: output,
	}, nil
}

type CopilotCLIProvider struct{}

func NewCopilotCLIProvider() *CopilotCLIProvider {
	return &CopilotCLIProvider{}
}

func (p *CopilotCLIProvider) Run(ctx context.Context, req AIRequest) (AIResult, error) {
	req.SessionID = ensureSessionID(req.SessionID)
	provider := ExternalCLIProvider{
		Name:             "copilot",
		EnvPrefix:        "KOROBOKCLE_COPILOT",
		DefaultBin:       "copilot",
		DefaultArgs:      copilotDefaultArgs(req.CopilotAllowTools),
		PreferOutputFile: true,
	}
	result, err := provider.Run(ctx, req)
	if err != nil {
		return result, err
	}
	return enrichJSONResult(result, req.SessionID)
}

type ClaudeCLIProvider struct{}

func NewClaudeCLIProvider() *ClaudeCLIProvider {
	return &ClaudeCLIProvider{}
}

func (p *ClaudeCLIProvider) Run(ctx context.Context, req AIRequest) (AIResult, error) {
	provider := ExternalCLIProvider{
		Name:       "claude",
		EnvPrefix:  "KOROBOKCLE_CLAUDE",
		DefaultBin: "claude",
		DefaultArgs: []string{
			"{{model_flag}}",
			"{{model}}",
		},
	}
	return provider.Run(ctx, req)
}

type CodexCLIProvider struct{}

func NewCodexCLIProvider() *CodexCLIProvider {
	return &CodexCLIProvider{}
}

func (p *CodexCLIProvider) Run(ctx context.Context, req AIRequest) (AIResult, error) {
	provider := ExternalCLIProvider{
		Name:       "codex",
		EnvPrefix:  "KOROBOKCLE_CODEX",
		DefaultBin: "codex",
		DefaultArgs: []string{
			"exec",
			"--json",
			"--output-last-message",
			"{{output_path}}",
			"--sandbox",
			"workspace-write",
			"{{model_flag}}",
			"{{model}}",
			"{{resume_command}}",
			"{{session_id}}",
		},
		PreferOutputFile: true,
	}
	result, err := provider.Run(ctx, req)
	if err != nil {
		return result, err
	}
	sessionID := strings.TrimSpace(req.SessionID)
	if sessionID == "" {
		sessionID = extractSessionID(result.Stdout)
	}
	return enrichJSONResult(result, sessionID)
}

type ExternalCLIProvider struct {
	Name             string
	EnvPrefix        string
	DefaultBin       string
	DefaultArgs      []string
	PreferOutputFile bool
}

func (p ExternalCLIProvider) Run(ctx context.Context, req AIRequest) (AIResult, error) {
	executable := firstNonEmpty(os.Getenv(p.EnvPrefix+"_BIN"), p.DefaultBin)
	args, err := loadProviderArgs(p.EnvPrefix+"_ARGS_JSON", p.DefaultArgs)
	if err != nil {
		return AIResult{}, fmt.Errorf("%s provider args: %w", p.Name, err)
	}
	promptInArgs := providerArgsContainPrompt(args)
	args = expandProviderArgs(args, req)
	debugEnabled := isTruthy(os.Getenv(p.EnvPrefix + "_DEBUG"))

	if _, err := exec.LookPath(executable); err != nil {
		return AIResult{}, fmt.Errorf("%s command %q is not available: %w", p.Name, executable, err)
	}

	workDir := firstNonEmpty(req.WorkDir, req.ArtifactDir, ".")
	cmd := exec.CommandContext(ctx, executable, args...)
	cmd.Dir = workDir

	outputPathPreexisting := false
	outputPathBefore := ""
	if req.OutputPath != "" {
		if raw, err := os.ReadFile(req.OutputPath); err == nil {
			outputPathPreexisting = true
			outputPathBefore = strings.TrimSpace(string(raw))
		} else if err != nil && !os.IsNotExist(err) {
			return AIResult{}, err
		}
	}

	var stdout bytes.Buffer
	var stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	if debugEnabled {
		fmt.Fprintf(&stderr, "[debug] provider=%s executable=%s workdir=%s prompt_in_args=%t args=%s\n", p.Name, executable, workDir, promptInArgs, debugArgsForLog(args))
		fmt.Fprintf(&stderr, "[debug] prompt=%s\n", req.Prompt)
	}
	if !promptInArgs && !strings.EqualFold(p.Name, "copilot") {
		cmd.Stdin = strings.NewReader(req.Prompt)
	}

	err = cmd.Run()
	if debugEnabled {
		fmt.Fprintf(&stderr, "[debug] provider=%s exit_err=%v stdout_bytes=%d stderr_bytes=%d\n", p.Name, err, stdout.Len(), stderr.Len())
	}
	result := AIResult{
		Stdout: stdout.String(),
		Stderr: stderr.String(),
		Output: strings.TrimSpace(stdout.String()),
	}

	if output := readProviderOutputFile(req.OutputPath); output != "" && (!outputPathPreexisting || output != outputPathBefore || result.Output == "" || p.PreferOutputFile && output != outputPathBefore) {
		result.Output = output
	}

	if err != nil {
		return result, fmt.Errorf("%s provider command failed: %w; stderr=%s", p.Name, err, strings.TrimSpace(result.Stderr))
	}
	if strings.TrimSpace(result.Output) == "" {
		return result, fmt.Errorf("%s provider returned empty output", p.Name)
	}
	return result, nil
}

func loadProviderArgs(envName string, defaults []string) ([]string, error) {
	raw := strings.TrimSpace(os.Getenv(envName))
	if raw == "" {
		return append([]string(nil), defaults...), nil
	}

	var args []string
	if err := json.Unmarshal([]byte(raw), &args); err != nil {
		return nil, fmt.Errorf("invalid JSON in %s: %w", envName, err)
	}
	return args, nil
}

func expandProviderArgs(args []string, req AIRequest) []string {
	replacements := map[string]string{
		"{{prompt}}":         req.Prompt,
		"{{model_flag}}":     modelFlag(req.Model),
		"{{model}}":          normalizedModelValue(req.Model),
		"{{work_dir}}":       req.WorkDir,
		"{{artifact_dir}}":   req.ArtifactDir,
		"{{output_path}}":    req.OutputPath,
		"{{output_file}}":    filepath.Base(req.OutputPath),
		"{{skill_name}}":     req.SkillName,
		"{{session_id}}":     strings.TrimSpace(req.SessionID),
		"{{resume_command}}": resumeCommand(req.SessionID),
	}

	expanded := make([]string, 0, len(args))
	for _, arg := range args {
		value := arg
		for placeholder, replacement := range replacements {
			value = strings.ReplaceAll(value, placeholder, replacement)
		}
		if strings.TrimSpace(value) == "" {
			continue
		}
		expanded = append(expanded, value)
	}
	return expanded
}

func providerArgsContainPrompt(args []string) bool {
	for _, arg := range args {
		if strings.Contains(arg, "{{prompt}}") {
			return true
		}
	}
	return false
}

func firstNonEmpty(values ...string) string {
	for _, value := range values {
		if strings.TrimSpace(value) != "" {
			return value
		}
	}
	return ""
}

func modelFlag(model string) string {
	if strings.TrimSpace(model) == "" || strings.EqualFold(strings.TrimSpace(model), "default") {
		return ""
	}
	return "--model"
}

func normalizedModelValue(model string) string {
	trimmed := strings.TrimSpace(model)
	if trimmed == "" || strings.EqualFold(trimmed, "default") {
		return ""
	}
	return trimmed
}

func isTruthy(value string) bool {
	switch strings.ToLower(strings.TrimSpace(value)) {
	case "1", "true", "yes", "on":
		return true
	default:
		return false
	}
}

func debugArgsForLog(args []string) string {
	if len(args) == 0 {
		return "[]"
	}
	quoted := make([]string, 0, len(args))
	for _, arg := range args {
		quoted = append(quoted, fmt.Sprintf("%q", arg))
	}
	return "[" + strings.Join(quoted, " ") + "]"
}

func copilotDefaultArgs(allowTools []string) []string {
	args := []string{
		"-p", "Read the instructions in {{artifact_dir}}/prompt.md and follow them. Use the repository root as the working directory and modify the repository files directly. Write the final response to {{output_path}}. Standard output may be used for progress logs only.",
		"-s",
		"--output-format",
		"json",
		"--session-id",
		"{{session_id}}",
		"{{model_flag}}", "{{model}}",
		"--add-dir",
		"{{artifact_dir}}",
		"--no-custom-instructions",
	}

	normalized := normalizeCopilotAllowTools(allowTools)
	if len(normalized) == 0 {
		normalized = normalizeCopilotAllowTools(config.DefaultCopilotAllowTools)
	}
	if len(normalized) == 0 {
		args = append(args, "--allow-all-tools")
	} else {
		args = append(args, "--allow-tool="+strings.Join(normalized, ","))
	}
	args = append(args, "--no-ask-user")
	return args
}

func ensureSessionID(sessionID string) string {
	trimmed := strings.TrimSpace(sessionID)
	if trimmed != "" {
		return trimmed
	}
	return uuid.NewString()
}

func enrichJSONResult(result AIResult, sessionID string) (AIResult, error) {
	result.SessionID = strings.TrimSpace(sessionID)
	events, err := parseJSONLEvents(result.Stdout)
	if err != nil {
		result.JSON = marshalProviderResultJSON(result.SessionID, result.Output, result.Stdout, result.Stderr, nil)
		return result, nil
	}
	result.JSON = marshalProviderResultJSON(result.SessionID, result.Output, result.Stdout, result.Stderr, events)
	return result, nil
}

func parseJSONLEvents(raw string) ([]map[string]any, error) {
	lines := splitNonEmptyLines(raw)
	events := make([]map[string]any, 0, len(lines))
	for _, line := range lines {
		var event map[string]any
		if err := json.Unmarshal([]byte(line), &event); err != nil {
			return nil, err
		}
		events = append(events, event)
	}
	return events, nil
}

func extractSessionID(raw string) string {
	events, err := parseJSONLEvents(raw)
	if err != nil {
		return ""
	}
	for _, event := range events {
		if strings.TrimSpace(stringValue(event, "type")) != "thread.started" {
			continue
		}
		if sessionID := firstNonEmpty(stringValue(event, "thread_id"), stringValue(event, "threadId")); sessionID != "" {
			return sessionID
		}
		if thread, ok := event["thread"].(map[string]any); ok {
			if sessionID := firstNonEmpty(stringValue(thread, "id"), stringValue(thread, "thread_id")); sessionID != "" {
				return sessionID
			}
		}
	}
	return ""
}

func stringValue(values map[string]any, key string) string {
	raw, ok := values[key]
	if !ok || raw == nil {
		return ""
	}
	switch value := raw.(type) {
	case string:
		return strings.TrimSpace(value)
	default:
		return strings.TrimSpace(fmt.Sprint(value))
	}
}

func resumeCommand(sessionID string) string {
	if strings.TrimSpace(sessionID) == "" {
		return ""
	}
	return "resume"
}

func marshalProviderResultJSON(sessionID string, output string, stdout string, stderr string, events []map[string]any) string {
	payload := map[string]any{
		"session_id": strings.TrimSpace(sessionID),
		"output":     output,
		"stdout":     stdout,
		"stderr":     stderr,
	}
	if len(events) > 0 {
		payload["events"] = events
	}
	raw, err := json.Marshal(payload)
	if err != nil {
		return ""
	}
	return string(raw)
}

func splitNonEmptyLines(value string) []string {
	lines := strings.Split(value, "\n")
	filtered := make([]string, 0, len(lines))
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" {
			continue
		}
		filtered = append(filtered, trimmed)
	}
	return filtered
}

func normalizeCopilotAllowTools(values []string) []string {
	normalized := make([]string, 0, len(values))
	seen := make(map[string]struct{}, len(values))
	for _, value := range values {
		trimmed := strings.TrimSpace(value)
		if trimmed == "" {
			continue
		}
		if _, ok := seen[trimmed]; ok {
			continue
		}
		seen[trimmed] = struct{}{}
		normalized = append(normalized, trimmed)
	}
	return normalized
}

func readProviderOutputFile(path string) string {
	raw, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(raw))
}

func ProviderFor(name string) (AIProvider, error) {
	switch strings.ToLower(strings.TrimSpace(name)) {
	case "", "mock":
		return NewMockProvider(), nil
	case "copilot":
		return NewCopilotCLIProvider(), nil
	case "claude":
		return NewClaudeCLIProvider(), nil
	case "codex":
		return NewCodexCLIProvider(), nil
	default:
		return nil, fmt.Errorf("unknown provider %q", name)
	}
}
