package skill

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

type MockProvider struct{}

func NewMockProvider() *MockProvider {
	return &MockProvider{}
}

func (p *MockProvider) Run(_ context.Context, req AIRequest) (AIResult, error) {
	output := "## Goal\n\nMock provider goal.\n\n## Scope\n\nMock provider scope.\n\n## Assumptions\n\n- Mock execution.\n\n## Proposed Changes\n\n- This artifact was generated by the mock provider.\n\n## Risks\n\n- Output is synthetic.\n\n## Test Strategy\n\n- Verify the artifact files are written.\n"
	if req.SkillName == "implement" {
		output = "## What Should Be Changed\n\n- Reviewed the approved design.\n\n## Suggested File Areas\n\n- Update the relevant source files.\n\n## Risks During Implementation\n\n- No repository code changes are applied by the mock provider.\n\n## Test Plan\n\n- Run the configured test profile.\n"
	}
	if req.SkillName == "review" {
		output = "## Summary\n\n- Reviewed the pull request context.\n\n## Findings\n\n- No real review was performed by the mock provider.\n\n## Recommendations\n\n- Verify the changes manually.\n\n## Notes\n\n- This output is synthetic.\n"
	}
	return AIResult{
		Stdout: "mock provider executed",
		Output: output,
	}, nil
}

type CopilotCLIProvider struct{}

func NewCopilotCLIProvider() *CopilotCLIProvider {
	return &CopilotCLIProvider{}
}

func (p *CopilotCLIProvider) Run(ctx context.Context, req AIRequest) (AIResult, error) {
	provider := ExternalCLIProvider{
		Name:        "copilot",
		EnvPrefix:   "KOROBOKCLE_COPILOT",
		DefaultBin:  "copilot",
		DefaultArgs: []string{"suggest", "-t", "general", "{{model_flag}}", "{{model}}", "{{prompt}}"},
	}
	return provider.Run(ctx, req)
}

type CodexCLIProvider struct{}

func NewCodexCLIProvider() *CodexCLIProvider {
	return &CodexCLIProvider{}
}

func (p *CodexCLIProvider) Run(ctx context.Context, req AIRequest) (AIResult, error) {
	provider := ExternalCLIProvider{
		Name:        "codex",
		EnvPrefix:   "KOROBOKCLE_CODEX",
		DefaultBin:  "codex",
		DefaultArgs: []string{"exec", "{{model_flag}}", "{{model}}", "{{prompt}}"},
	}
	return provider.Run(ctx, req)
}

type ExternalCLIProvider struct {
	Name        string
	EnvPrefix   string
	DefaultBin  string
	DefaultArgs []string
}

func (p ExternalCLIProvider) Run(ctx context.Context, req AIRequest) (AIResult, error) {
	executable := firstNonEmpty(os.Getenv(p.EnvPrefix+"_BIN"), p.DefaultBin)
	args, err := loadProviderArgs(p.EnvPrefix+"_ARGS_JSON", p.DefaultArgs)
	if err != nil {
		return AIResult{}, fmt.Errorf("%s provider args: %w", p.Name, err)
	}
	promptInArgs := providerArgsContainPrompt(args)
	args = expandProviderArgs(args, req)

	if _, err := exec.LookPath(executable); err != nil {
		return AIResult{}, fmt.Errorf("%s command %q is not available: %w", p.Name, executable, err)
	}

	workDir := firstNonEmpty(req.WorkDir, req.ArtifactDir, ".")
	cmd := exec.CommandContext(ctx, executable, args...)
	cmd.Dir = workDir

	var stdout bytes.Buffer
	var stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	if !promptInArgs {
		cmd.Stdin = strings.NewReader(req.Prompt)
	}

	err = cmd.Run()
	result := AIResult{
		Stdout: stdout.String(),
		Stderr: stderr.String(),
		Output: strings.TrimSpace(stdout.String()),
	}

	if result.Output == "" {
		if raw, readErr := os.ReadFile(req.OutputPath); readErr == nil {
			result.Output = string(raw)
		}
	}

	if err != nil {
		return result, fmt.Errorf("%s provider command failed: %w; stderr=%s", p.Name, err, strings.TrimSpace(result.Stderr))
	}
	if strings.TrimSpace(result.Output) == "" {
		return result, fmt.Errorf("%s provider returned empty output", p.Name)
	}
	return result, nil
}

func loadProviderArgs(envName string, defaults []string) ([]string, error) {
	raw := strings.TrimSpace(os.Getenv(envName))
	if raw == "" {
		return append([]string(nil), defaults...), nil
	}

	var args []string
	if err := json.Unmarshal([]byte(raw), &args); err != nil {
		return nil, fmt.Errorf("invalid JSON in %s: %w", envName, err)
	}
	return args, nil
}

func expandProviderArgs(args []string, req AIRequest) []string {
	replacements := map[string]string{
		"{{prompt}}":       req.Prompt,
		"{{model_flag}}":   modelFlag(req.Model),
		"{{model}}":        req.Model,
		"{{work_dir}}":     req.WorkDir,
		"{{artifact_dir}}": req.ArtifactDir,
		"{{output_path}}":  req.OutputPath,
		"{{output_file}}":  filepath.Base(req.OutputPath),
		"{{skill_name}}":   req.SkillName,
	}

	expanded := make([]string, 0, len(args))
	for _, arg := range args {
		value := arg
		for placeholder, replacement := range replacements {
			value = strings.ReplaceAll(value, placeholder, replacement)
		}
		if strings.TrimSpace(value) == "" {
			continue
		}
		expanded = append(expanded, value)
	}
	return expanded
}

func providerArgsContainPrompt(args []string) bool {
	for _, arg := range args {
		if strings.Contains(arg, "{{prompt}}") {
			return true
		}
	}
	return false
}

func firstNonEmpty(values ...string) string {
	for _, value := range values {
		if strings.TrimSpace(value) != "" {
			return value
		}
	}
	return ""
}

func modelFlag(model string) string {
	if strings.TrimSpace(model) == "" {
		return ""
	}
	return "--model"
}

func ProviderFor(name string) (AIProvider, error) {
	switch strings.ToLower(strings.TrimSpace(name)) {
	case "", "mock":
		return NewMockProvider(), nil
	case "copilot":
		return NewCopilotCLIProvider(), nil
	case "codex":
		return NewCodexCLIProvider(), nil
	default:
		return nil, fmt.Errorf("unknown provider %q", name)
	}
}
