rules:
    - id: rule-1
      name: issue
      repositories:
        - https://github.com/coco-papiyon/korobokcle
      target: issue
      labels: []
      titlePattern: ""
      authors: []
      assignees:
        - coco-papiyon
      excludeDraftPR: true
      provider: ""
      model: ""
      skillSet: default
      testProfile: go-default
      enabled: true
    - id: rule-2
      name: PR
      repositories:
        - https://github.com/coco-papiyon/korobokcle
      target: pull_request
      labels: []
      titlePattern: ""
      authors: []
      assignees: []
      excludeDraftPR: true
      provider: ""
      model: ""
      skillSet: default
      testProfile: go-default
      enabled: true
